# Generated by Django 5.1.15 on 2026-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(default='CALL', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_records', to='investigations.investigation')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_communications', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_communications', to='entities.entity')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('transaction_type', models.CharField(default='WIRE_TRANSFER', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='investigations.investigation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='entities.entity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='entities.entity')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(default='CHECK_IN', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='entities.entity')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('KNOWS', 'Knows'), ('COMMUNICATED_WITH', 'Communicated With'), ('CALLED', 'Called'), ('TRANSFERRED_TO', 'Transferred To'), ('OWNS', 'Owns'), ('ASSOCIATED_WITH', 'Associated With'), ('LOCATED_AT', 'Located At'), ('WORKS_FOR', 'Works For'), ('TRAVELLED_TO', 'Travelled To'), ('PARTICIPATED_IN', 'Participated In'), ('LINKED_TO', 'Linked To'), ('MENTIONED_WITH', 'Mentioned With')], default='ASSOCIATED_WITH', max_length=40)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(blank=True, default='MANUAL', max_length=255)),
                ('evidence', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='investigations.investigation')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='entities.entity')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'unique_together': {('investigation', 'source_entity', 'target_entity', 'relationship_type')},
            },
        ),
    ]
