# Generated by Django 5.1.15 on 2026-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('DISMISSED', 'Dismissed'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('related_entities', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'), models.Index(fields=['alert_type'], name='alerts_aler_alert_t_e287ad_idx')],
            },
        ),
    ]
