# Generated by Django 5.1.15 on 2026-08-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('LOCATION', 'Location'), ('VEHICLE', 'Vehicle'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('ACCOUNT', 'Account'), ('CASE', 'Case'), ('EVENT', 'Event'), ('SOCIAL_PROFILE', 'Social Profile'), ('DOCUMENT', 'Document')], default='PERSON', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(blank=True, default='MANUAL', max_length=255)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='investigations.investigation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityMergeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('match_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Merged / Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates', to='investigations.investigation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_merge_candidates', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_merge_candidates', to='entities.entity')),
            ],
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['normalized_name'], name='entities_en_normali_292779_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='entities_en_entity__73cf99_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['external_reference'], name='entities_en_externa_90d248_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['created_at'], name='entities_en_created_ce9a5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitymergecandidate',
            unique_together={('source_entity', 'target_entity')},
        ),
    ]
