# Generated by Django 5.1.15 on 2026-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('FIR', 'First Information Report (FIR)'), ('POLICE_REPORT', 'Police Report'), ('SURVEILLANCE_NOTE', 'Surveillance Note'), ('INTELLIGENCE_NOTE', 'Intelligence Note'), ('CDR_LOG', 'Call Detail Record (CDR)'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other Document')], default='POLICE_REPORT', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('source', models.CharField(blank=True, default='UPLOAD', max_length=255)),
                ('hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
